#102 client  forgot password before logged in
jbt-it/neomdb pull request #112
Opened 2021-06-29 19:20 UTC by johannesfbraun

2021-06-29 19:22 UTC, johannesfbraun commented
closes #112 
frontend to send a reset link to the users mail
frontend to click on the resetPW link and send a new PW

2021-06-30 09:49 UTC, LennartRukower requested changes
There are a few minor things I noticed.
I realized that some of these things (english names for routes and comments beginning with a small lettter) also occur in the ChangePassword-branch (#33), which was already merged.

@christophtrybek, what do you think is the best course of action? Should @johannesfbraun make a new issue and branch to "fix" these things?

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ForgotPassword.tsx
> + *
Delete empty line.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ForgotPassword.tsx
> +   * check if input is an email
Start comment with a big letter.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ForgotPassword.tsx
> +   * return a warning if it is not a valid email
Start comment with a big letter.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +/**
It makes more sense to call this component/page "ResetPassword"

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * check if the new PW is okay: min 8 chars; mind 1 je num/a-z/A-Z
Start comment with a big letter.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * check if the new PW is okay: min 8 chars; mind 1 je num/a-z/A-Z
Please don't use abbreviation like PW.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * new password fild
Start comment with a big letter.
This is not a sufficient comment for this function. What does this function do?

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * new password field validation
Start comment with a big letter.
This is not a sufficient comment for this function. What does this function do?

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * check if input is an email
Start comment with a big letter.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * return a warning if it is not a valid email
Start comment with a big letter.

2021-06-30 09:49 UTC, LennartRukower commented on client/src/ts/members/ResetForgotPassword.tsx
> +   * if res is code 200
Start comment with a big letter.

2021-06-30 09:49 UTC, LennartRukower commented on server/src/members/membersController.ts
> +  res.status(200).send("not implemented");
Stubs in the backend should not be used.
Implement it in another branch and merge it before doing a pull request of the frontend.

@christophtrybek, your thoughts?

2021-06-30 09:49 UTC, LennartRukower commented on server/src/members/membersController.ts
> +  res.status(200).send("not implemented");
Stubs in the backend should not be used.
Implement it in another branch and merge it before doing a pull request of the frontend.

@christophtrybek, your thoughts?

2021-06-30 09:49 UTC, LennartRukower commented on server/src/members/membersController.ts
> + * @param req email
This is not a sufficient comment for this function. What does this function do?

2021-06-30 09:49 UTC, LennartRukower commented on server/src/members/membersController.ts
> + * @param req email
This is not a sufficient comment for this function. What does this function do?

2021-06-30 09:50 UTC, LennartRukower commented
> closes #112
> frontend to send a reset link to the users mail
> frontend to click on the resetPW link and send a new PW

These things should be in the description of the pull request.

2021-06-30 11:07 UTC, johannesfbraun commented on client/src/ts/members/ResetForgotPassword.tsx
> +/**
I think the "Forgot" helps to clarify that it belongs to "ForgotPassword"

2022-04-04 16:48 UTC, qnewald requested changes
When entering an E-Mail in the Forgot Password E-Mail field and hitting "send password" the page sometimes refreshes and the message that an email was sent if the email is correct will not be displayed.

2022-04-04 16:48 UTC, qnewald commented on client/src/ts/members/ResetForgotPassword.tsx
> +import React, { useState, useContext } from "react";
"useContext" Remove unused imports

2022-04-04 16:48 UTC, qnewald commented on client/src/ts/members/ForgotPassword.tsx
> +          If you gave your correct email, you should recieve a new password
Mention that an email will be sent with instructions on how to reset the password.
For example: "If the entered email exists, we have sent you an email with instructions on how to reset your password."

2023-06-11 18:32 UTC, closed without merging