#121 add prettier config
jbt-it/neomdb pull request #122
Opened 2021-08-19 09:22 UTC by LennartRukower

Added prettier file and options for better automatic formatting.

See prettier documentation for an in depth explanation of the different options:
https://prettier.io/docs/en/options.html

Closes #121

2021-08-25 10:10 UTC, johannesfbraun approved these changes
LGTM

2021-09-20 15:48 UTC, christophtrybek requested changes
Got a Question regarding the Proxies

2021-09-22 13:14 UTC, LennartRukower commented on client/package.json
> +  "proxy": "https://localhost:3030",
This is a change from the pull request #115.
It has nothing to do with the prettier config.

2021-11-29 07:16 UTC, christophtrybek approved these changes
LGTM

2021-12-20 19:18 UTC, merged