#85 directors history
jbt-it/neomdb pull request #125
Opened 2021-08-21 14:43 UTC by lisa-bai

created directors history

closes #85

2021-08-21 19:57 UTC, johannesfbraun requested changes
Well done only minor changes :)

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +      console.log(error);
no console logs

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +        director.nachname.toLowerCase().includes(searchFilter.toLowerCase())
trailing whitespace

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +
trailing whitespace

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +
trailing whitespace

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +
trailing whitespace

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +
trailing whitespace

2021-08-21 19:57 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +                    {`${director.vorname} ${director.nachname}`}
I think a link to the user profile, when clicking on the name would be good

2021-08-22 09:24 UTC, LennartRukower commented on client/src/ts/members/DirectorHistory.tsx
> +      console.log(error);
Until now console logs were the standard way of dealing with errors.

But after the implementation of Snackbars (see #78) the usage of Snackbars for displaying errors is the way to go.

2021-08-22 09:44 UTC, LennartRukower requested changes
Very good first pr!
Please fix the small formatting mistakes and rerequest my review after that.

Please check if your typescript linter (TSLint) is activated in VSC. With this extension the formatting mistakes are visually indicated by a warning.

2021-08-22 09:44 UTC, LennartRukower commented on client/src/ts/members/DirectorHistory.tsx
> +
Why is here an empty line?

2021-08-22 09:44 UTC, LennartRukower commented on client/src/ts/members/DirectorHistory.tsx
> +
No empty line

2021-08-22 09:44 UTC, LennartRukower commented on client/src/ts/members/DirectorHistory.tsx
> +
No empty line

2021-08-22 09:44 UTC, LennartRukower commented on client/src/ts/members/DirectorHistory.tsx
> +
No empty line

2021-08-22 09:44 UTC, LennartRukower commented on client/src/ts/members/DirectorHistory.tsx
> +
No empty line

2021-11-04 18:28 UTC, johannesfbraun requested changes
looks good; only the trailing whitespace is still there

2021-11-04 18:28 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +        director.nachname.toLowerCase().includes(searchFilter.toLowerCase())
trailing whitespace (no-trailing-whitespace)

2021-11-04 18:28 UTC, johannesfbraun commented on client/src/ts/members/DirectorHistory.tsx
> +        director.nachname.toLowerCase().includes(searchFilter.toLowerCase())
trailing whitespace (no-trailing-whitespace)

2021-11-21 16:08 UTC, jbt-it approved these changes
LGTM

2021-11-21 21:23 UTC, merged