#79 implement department overview
jbt-it/neomdb pull request #138
Opened 2021-12-28 11:52 UTC by KevinGus

Closes #79 
Implemented department overview page.

2021-12-28 12:50 UTC, johannesfbraun requested changes
Please fix the errors with the .get methods

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +  Table,
Table - IconButton not used, so please remove

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +import { NoEncryptionTwoTone } from "@material-ui/icons";
Not used please remove

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +  useEffect(() => {
@typescript-eslint/no-unused-vars
  Line 208:6:  React Hook useEffect has missing dependencies: 'getCurrentDirectors', 'getDepartmentMembers', and 'getDepartments'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +  const getDepartments: VoidFunction = () => {
Gets a 304 Error

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +  const getDepartmentMembers: VoidFunction = () => {
Gets a 404 error

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +  const getCurrentDirectors: VoidFunction = () => {
Gets a 404 error

2021-12-28 12:50 UTC, johannesfbraun commented on client/src/ts/members/DepartmentOverview.tsx
> +  return (
No data is displayed, as all the .get are returned an error message

2022-01-10 17:39 UTC, LennartRukower requested changes

2022-01-10 17:39 UTC, LennartRukower commented on client/src/ts/members/DepartmentOverview.tsx
> +  }, []);
This useEffect has missing dependencies.
(Follow the instructions of TSLint, which should already recommend dependencies).
See Issue #137 for a similiar use case.

2022-01-10 17:39 UTC, LennartRukower commented on client/src/ts/members/DepartmentOverview.tsx
> +   * Filters cirectors in their departments
Spelling mistake: "cirectors"

2022-11-07 00:02 UTC, JanMueller31 approved these changes
lgtm

2022-11-07 00:14 UTC, merged