#139 add delegate info to authcontext
jbt-it/neomdb pull request #140
Opened 2021-12-28 15:02 UTC by LennartRukower

Added delegate information to the server and changed the permission type in the frontend accordingly.

2021-12-28 21:20 UTC, johannesfbraun requested changes
See comment

2021-12-28 21:20 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +            if (directorPermissionsResult.length !== 0) {
The order the permissions are added doesn't seem right to me

2021-12-28 21:20 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +            if (directorPermissionsResult.length !== 0) {
A person that has no directorPermissionResult would get no permissions at all

2021-12-29 08:41 UTC, johannesfbraun requested changes
LGTM

2021-12-29 08:42 UTC, johannesfbraun approved these changes
LGTM

2021-12-29 12:07 UTC, qnewald approved these changes
LGTM

2021-12-29 12:07 UTC, qnewald commented on client/src/ts/global/App.tsx
> +          console.log(res.data.permissions);
log statement, remove if unnecessary

2021-12-29 12:16 UTC, merged