#103 server forgot password server sends new password
jbt-it/neomdb pull request #141
Opened 2021-12-29 16:19 UTC by johannesfbraun

closes #103

2022-04-10 11:00 UTC, LennartRukower requested changes
You didn't push you changes of package.json.
Because you use a new module `nodemailer`, this dependency should be in package.json.

Good PR. Just a few minor things. Please request my review again, after resolving my comments :)

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
> +                    // Send email with correct URL to usermail
I would move the code for sending an email to a separate file in utils, which provides email functionality.
Sending an email is sth. that will be used often, therefore it would make sense to implement a function just for that.

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
>          res.status(204).send("User does not exist");
Should be a 404-Status

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
> +          .catch((_err) => {
What is the reasoning of changing all occurrences of `err` to `_err`?

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
> +                    const mailOptions = {
Email-text should be in german.

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
>   * The mail and the key in the url are then checked to se if it is a valid pair
Typo: "... to see if"

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
> +        res.status(200).send();
But wouldn't that be an invalid input from the client, meaning the status code `422` should be returned (https://stackoverflow.com/questions/7939137/what-http-status-code-should-be-used-for-wrong-input)?
In the frontend I would check for 200 and then assume, that the password was reset successfully. Therefore it would make sense to differentiate between the different possibilities.

2022-04-10 11:00 UTC, LennartRukower commented on server/src/members/membersController.ts
> +          res.status(200).send();
Instead of using `200`, `410` (=Gone) or `403` (=Forbidden) could be used.
In the frontend I would check for 200 and then assume, that the password was reset successfully. Therefore it would make sense to differentiate between the different possibilities.

2022-05-30 07:05 UTC, lisa-bai commented on server/src/members/membersTypes.ts
> +};
comment

2022-05-30 07:05 UTC, lisa-bai commented on server/src/members/membersTypes.ts
> +/**
comment

2023-06-11 10:17 UTC, closed without merging