#27 add permissions overview
jbt-it/neomdb pull request #152
Opened 2022-02-24 18:10 UTC by BorchBe99

closes #27

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Calls to console.log are not allowed

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Calls to console.log are not allowed

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +            console.log(res.data);
Calls to console.log are not allowed

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Calls to console.log are not allowed

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +            console.log(res.data);
Calls to console.log are not allowed

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Calls to console.log are not allowed

2022-03-13 16:59 UTC, lisa-bai commented on client/src/ts/members/PermissionsOverview.tsx
> +  const { auth, dispatchAuth } = useContext(AuthContext);
unused constant dispatchAuth

2022-03-31 16:27 UTC, BorchBe99 commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Fixed

2022-03-31 16:27 UTC, BorchBe99 commented on client/src/ts/members/PermissionsOverview.tsx
> +            console.log(res.data);
Fixed

2022-03-31 16:27 UTC, BorchBe99 commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Fixed

2022-03-31 16:27 UTC, BorchBe99 commented on client/src/ts/members/PermissionsOverview.tsx
> +            console.log(res.data);
Fixed

2022-03-31 16:27 UTC, BorchBe99 commented on client/src/ts/members/PermissionsOverview.tsx
> +        console.log(error);
Fixed

2022-03-31 16:27 UTC, BorchBe99 commented on client/src/ts/members/PermissionsOverview.tsx
> +  const { auth, dispatchAuth } = useContext(AuthContext);
Fixed

2022-04-02 10:04 UTC, jbt-it requested changes
-Please add a it to the navigation under "Mitglieder"
-"createPermission" should also return the changed state?

2022-06-22 12:55 UTC, BorchBe99 commented
Overview of how Permissions work at current sate:
- The permissions overview  page can only be seen by directors and members with at least one granted permission.
- Members can be applied a director role, but not on this page.
- Only directors can grant and revoke permissions only to other members, if canDeligate is set to 1.
- Members can't grant or revoke permissions.
- Directors can't be granted or revoked any permission.

A test database with a txt file has been uploded to NextCloud

2022-09-27 15:19 UTC, LennartRukower approved these changes
Very good! This can finally be merged :)

2022-09-27 15:21 UTC, merged