#28 add member management page
jbt-it/neomdb pull request #154
Opened 2022-03-23 19:31 UTC by qnewald

Adds a new page that allows admins to change the status of current members. At this time it is not possible to create new members, because of a dependency on another issue.

2022-03-31 10:23 UTC, qnewald commented
Closes #28

2022-04-02 10:16 UTC, jbt-it requested changes
- Add a way to navigate to the subpage
- give options for the Trainee Generation
- add the "Trainee seit field"

2022-04-02 10:16 UTC, jbt-it commented on client/src/ts/members/MemberManagement.tsx
> +        console.log(error);
no console log

2022-04-02 10:16 UTC, jbt-it commented on client/src/ts/members/MemberManagement.tsx
> +    let payload = {
use const

2022-04-02 10:16 UTC, jbt-it commented on client/src/ts/members/MemberManagement.tsx
> +      .catch((error) => {});
Empty catch

2023-07-23 17:14 UTC, arisb1470 commented
Looks good! There are two issues that I found: 
When trying to change the status to "ausgetretenes Mitglied, following error message pops up: "Request failed with status code 500"
Secondly, trying to search for members doesn't appear to be working. When entering any symbol into the searchbar, the site goes blank.

2023-08-15 11:01 UTC, merged