#135 client ips
jbt-it/neomdb pull request #190
Opened 2022-06-27 15:07 UTC by DarkoCutkovic

- Implemented Frontend for Internal Project Page
- Dummy Object Inserted to display data

2022-06-27 16:17 UTC, LennartRukower requested changes
Good first PR!
But it still needs work.

2022-06-27 16:17 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  //TODO neusten develop pullen und permissionsdings holen was in authb ist
Is this still a TODO?

2022-06-27 16:17 UTC, LennartRukower commented on client/src/ts/global/App.tsx
> -  const { auth, dispatchAuth } = useContext(AuthContext);
It seems like you prettier is not working.
Please check if you have the necessary [VSC extensions](https://github.com/jbt-it/neomdb/wiki/Extensions-f%C3%BCr-VSC).

2022-07-24 18:15 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  ] = useContext(AuthContext);
@DarkoCutkovic, you should only resolve conversations if you fixed the problem.

2022-07-24 18:15 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  //TODO neusten develop pullen und permissionsdings holen was in authb ist
@DarkoCutkovic, you should only resolve conversations if you fixed the problem.

2022-07-24 18:16 UTC, LennartRukower requested changes
Nothing changed. Please make sure you pushed your committed changes, before re-requesting a review.

2022-08-18 06:47 UTC, LennartRukower requested changes
There are still some things that must be resolved.

2022-08-18 06:47 UTC, LennartRukower commented on client/src/ts/global/App.tsx
> +        <PrivateRoute exact path="/internalproject" component={InternalProject} />
Please use a german name for the path.

2022-08-18 06:47 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +      mounted = false;
`mounted` is not used. Look again to other fetch functions (e.g. in `MemberPage.tsx`) to see how it is correctly used.
Does your IDE not show you, when variables are not used? (yellow underlined)

2022-08-18 06:47 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  useEffect(getInternalProjectDetails);
This is line is dangerous!
Currently every second the data is fetched again.
Therefore the whole application begins to slow down and you cannot do anything else after visiting "internalProject".
Suggestions: `   useEffect(getInternalProjectDetails, []);`
Please read again about useEffect: https://alexsidorenko.com/blog/useeffect/#running-effects-conditionally

2022-10-09 12:25 UTC, LennartRukower requested changes

2022-10-09 12:25 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  const rendetInternalProjectInformationDialog: VoidFunction = () => {
Spelling mistake. Should be `renderInternalProjectInformationDialog`.

2022-10-09 12:25 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +      >
Is it necessary that all input fields are required?
Normally the information about an internal project is successively updated and therefore everything except for "Name", "Kürzel" and "Traineegeration" should be not required.

2022-10-09 12:25 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +                //     isOwner || permissionList.includes(1)
This is commented out, because you will implement this together with the api calls, correct?

2022-10-20 17:44 UTC, LennartRukower requested changes
Almost finished.
There are only two small issues left.

2022-10-20 17:44 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  type IpInfoType = {
Add this `IpInfoType` to a specific traineesTypes file.
Just like in the members module.

2022-10-20 17:44 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +      qualitaetsmanager: "Franziska Keßler, Niklas Kamilli, Marco Hintennach",
Please use "made-up names" and not actual names from our members.

2023-07-09 19:30 UTC, LennartRukower requested changes
Very good work!
I only have small issues regarding the code.
I tried to make as much suggestions as possible.

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
Please move single components into the components folder.

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  const { auth, dispatchAuth } = useContext(AuthContext);
dispatchAuth is not used.
```suggestion
  const { auth } = useContext(AuthContext);
```

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +  const [internalProjectDetails, setInternalProjectDetails] = useState<traineesTypes.IpInfoType>();
internatlProjectDetails are set but never used.

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +          <br></br>
`</br>` is an invalid html element because br is self closing.
Use `<br>` or `<br/>`.

```suggestion
          <br/>
```

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProject.tsx
> +          <br></br>
`</br>` is an invalid html element because br is self closing.
Use `<br>` or `<br/>`.

```suggestion
          <br/>

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProjectDetail.tsx
Please move single components into the components folder.

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProjectDetail.tsx
> +export const InternalProjectDetail: React.FC<DetailProps> = ({ name, value }) => {
This component is missing its comment.
```suggestion
/**
 * Renders a value with its corresponding name
 */
export const InternalProjectDetail: React.FC<DetailProps> = ({ name, value }) => {
```

2023-07-09 19:30 UTC, LennartRukower commented on client/src/ts/trainees/InternalProjectDetail.tsx
> +export const InternalProjectDetail: React.FC<DetailProps> = ({ name, value }) => {
This component is a general component which can be used outside of the internal project context.
Maybe rename it, e.g. to Detail.

2023-08-02 13:04 UTC, JanMueller31 commented on client/src/ts/trainees/InternalProject.tsx
Will move components and other files when restructuring the front end.

2023-08-02 13:04 UTC, JanMueller31 commented on client/src/ts/trainees/InternalProject.tsx
Will move components when restructuring the front end folder structure

2023-08-02 13:08 UTC, JanMueller31 commented on client/src/ts/trainees/InternalProject.tsx
> +  const [internalProjectDetails, setInternalProjectDetails] = useState<traineesTypes.IpInfoType>();
Will be used when the api call for the ip details is complete

2023-08-02 18:01 UTC, LennartRukower requested changes
I've only found a small issue regarding the use of the dialog states.

2023-08-02 18:02 UTC, LennartRukower commented on client/src/ts/trainees/InternalProjectInformationDialog.tsx
> +  const onSubmit = () => {
@JanMueller31, this suggestion was not applied.
Is there a reason for it? Do you disagree with the way submit events should be handled?

2023-11-24 16:23 UTC, LennartRukower requested changes
Good work!
I found a few issues. You should also run "Organize Imports" to remove unused imports (Open command palette and select "Organize Imports").

2023-11-24 16:23 UTC, LennartRukower commented on client/src/utils/dateUtils.ts
> +export const transformDateToReadableString = (date: Date) => {
Please add a descriptive comment to this function.

2023-11-24 16:23 UTC, LennartRukower commented on client/src/utils/stringUtils.ts
> +export function stringAvatar(name: string) {
Please add a descriptive comment.

2023-11-24 16:23 UTC, LennartRukower commented on client/src/utils/stringUtils.ts
> +export function stringAvatar(name: string) {
Maybe change the function name.

2023-11-24 16:23 UTC, LennartRukower commented on client/src/utils/stringUtils.ts
> +  function stringToColor(string: string) {
Move this function outside of the parent function.

2023-12-12 16:09 UTC, JanMueller31 commented on client/src/components/general/MemberSelection.tsx
> +import React from "react";
Yes it is a general component used in several different pages such as interal projects, events and regular projects

2024-02-12 17:26 UTC, closed without merging