two functions added to retrieve the current trainees and the current …
jbt-it/neomdb pull request #196
Opened 2022-09-26 14:22 UTC by jbt-it

The folder trainees for the trainees module was added as well as the respective files for the controller, routes and types. In addtion the lines of code were added to the app.ts file so the routes can be used.

For this Issue two functions and routes were added: the `retrieveCurrentTrainees` and `retrieveCurrentIPs` function and their respective routes "/" and "/currentIPs".

The function `retrieveCurrentTrainees` is supposed to "get the data to display the trainee generation". By checking the URL GET https://localhost:3030/trainees with Postman a JSON-object with the current trainees should be received if logged in.

The function `retrieveCurrentIPs` is supposed to "get the data to display the IPs". By checking the URL GET https://localhost:3030/trainees/currentIPs with Postman a JSON-object with the current trainees should be received if logged in.

Closes #128

2022-10-20 17:16 UTC, LennartRukower requested changes
A few minor issues and one question about the third implemented function.

Please check if you have prettier and TSLint activated because there are a few formatting issues in your files.

2022-10-20 17:16 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +    for (var i = 1; i< numberOfGenerations + 1;i++){
use `let` instead of `var`.

2022-10-20 17:16 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +export const retrieveTraineeGenerations = (req: Request, res: Response): void => {
There is no route for this controller function.
How should this function be tested?

2023-06-27 11:38 UTC, LennartRukower commented on client/src/ts/global/App.tsx
> +        console.log(err);
Is this console log necessary? Why was this added?

2023-06-27 11:40 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +        res.status(404).send("IPs not found");
404 should only be used, if a specific resource is not found.
E.g. If you want to retrieve an IP with id 66 and this IP does not exist, a 404 would be thrown.
If we retrieve all IPs and there are no IPs we do not need to send an error message. The user gets an empty array, which is sufficient and better for handling on the frontend.

2023-06-27 11:42 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +export const retrieveAllTrainees = (req: Request, res: Response): void => {
Maybe call this function `retrieveAllTraineesWithIPs`

2023-06-27 11:43 UTC, LennartRukower commented on server/src/trainees/traineesTypes.ts
> +export type retrieveAllTraineesQueryResult = {
Call this type `GetAllTraineesWithIPsQueryResult`

2023-06-27 11:44 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +        res.status(404).send("Trainees not found");
404 should only be used, if a specific resource is not found.
E.g. If you want to retrieve an IP with id 66 and this IP does not exist, a 404 would be thrown.
If we retrieve all IPs and there are no IPs we do not need to send an error message. The user gets an empty array, which is sufficient and better for handling on the frontend.

2023-06-27 11:47 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +    .then((result: traineesTypes.retrieveAllTraineesQueryResult[]) => {
Is `traineesTypes.retrieveAllTraineesQueryResult[]` the correct type for this query result?
`export type retrieveAllTraineesQueryResult = {
  generation: number;
  mitgliedID: number;
  vorname: string;
  nachname: string;
  internesprojekt: string;
};` -> internesprojekt is a string?

2023-06-27 14:23 UTC, JanMueller31 commented on server/src/trainees/traineesRoutes.ts
> + router.get("/currentIPs", traineesController.retrieveCurrentIPs);
Done

2023-06-27 14:23 UTC, JanMueller31 commented on server/src/trainees/traineesController.ts
> +    });
Changed

2023-06-27 14:26 UTC, LennartRukower requested changes

2023-06-27 14:26 UTC, LennartRukower commented on client/src/ts/global/App.tsx
> +        console.log(err);
```suggestion
```

2023-08-12 12:55 UTC, LennartRukower approved these changes
LGTM, nice work

2023-08-12 13:18 UTC, merged