#134 server  trainee selection
jbt-it/neomdb pull request #229
Opened 2022-12-08 18:36 UTC by BorchBe99

2023-03-21 15:15 UTC, BorchBe99 commented
Addes routes to retrieve information about trainees, such as choices of mentor, internal project or department.

2023-03-31 21:37 UTC, LennartRukower requested changes
I did not yet test the functionality but I looked through the code and found a few small issues.
Using doc comments and describing how the requests look like is a good idea!

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * Definition of the handler functions for the members module
These are handler functions for the trainees module not the members module

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
Please use camel case variables:
```suggestion
 * @param req generationID
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      [req.body.generation_ID]
Please use camel case variables:
```suggestion
      [req.body.generationID]
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
Is the request parameter not more than just the generationID?
The request paramter is an object with a body object which has `generationID` as an attribute.

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
See other comments above regarding param.

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      [req.body.generation_ID]
Please use camel case variables:
```suggestion
      [req.body.generationID]
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req null
The request param is not null

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req wahl_start and wahl_ende in form of DATETIME, generationID
If you want to describe what body attribute should be given for the request you can write it as follows:
```suggestion
 * @param {Request} req request object
 * @param {Date} req.body.votingStart
 * @param {Date} req.body.votingEnd
 * @param {number} req.body.generationID
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      req.body.wahl_start,
Please use camel case and english variable names

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      req.body.wahl_ende,
Please use camel case and english variable names

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req internesprojektID, mentorID, ressortID, mitgliedID
See comment with suggestion above

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req mitglied_ID, generation_ID
See comment with suggestion above

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      req.body.mitglied_ID,
Please use camel case and english variable names

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      req.body.generation_ID,
Please use camel case

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
See comment with suggestion above

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
You should also use type annotations for the parameters (see suggestion a few comments below).

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +export const GetMentorsOfGeneration = (req: Request, res: Response): void => {
Please use camel case for function names:
```suggestion
export const getMentorsOfGeneration = (req: Request, res: Response): void => {
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +export const GetInternalProjectsOfGeneration = (req: Request, res: Response): void => {
Please use camel case for function names:
```suggestion
export const getInternalProjectsOfGeneration = (req: Request, res: Response): void => {
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeTypes.ts
> +export type GetGenerations = {
For more consistency please add `Result` to the type name:
```suggestion
export type GetGenerationsResult = {
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeTypes.ts
> +export type GetMentorsOfGeneration = {
For more consistency please add `Result` to the type name:
```suggestion
export type GetMentorsOfGenerationResult = {
```

2023-03-31 21:37 UTC, LennartRukower commented on server/src/trainee/traineeTypes.ts
> +export type GetInternalProjectOfGeneration = {
For more consistency please add `Result` to the type name:
```suggestion
export type GetInternalProjectOfGenerationResult = {
```

2023-05-06 10:11 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * Definition of the handler functions for the members module
Is Updated

2023-05-06 10:14 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
fixed

2023-05-06 10:15 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
fixed

2023-05-06 10:17 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      [req.body.generation_ID]
fixed

2023-05-06 10:17 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req null
fixed

2023-05-06 10:18 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req wahl_start and wahl_ende in form of DATETIME, generationID
fixed

2023-05-06 10:20 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      req.body.wahl_start,
fixed

2023-05-06 10:20 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      req.body.wahl_ende,
fixed

2023-05-06 10:21 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req internesprojektID, mentorID, ressortID, mitgliedID
fixed

2023-05-06 10:24 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req mitglied_ID, generation_ID
fixed

2023-05-06 10:24 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      req.body.mitglied_ID,
fixed

2023-05-06 10:25 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      req.body.generation_ID,
fixed

2023-05-06 10:26 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> + * @param req generation_ID
fixed

2023-05-06 10:27 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +export const GetMentorsOfGeneration = (req: Request, res: Response): void => {
fixed

2023-05-06 10:30 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +export const GetInternalProjectsOfGeneration = (req: Request, res: Response): void => {
fixed

2023-05-06 10:32 UTC, BorchBe99 commented on server/src/trainee/traineeTypes.ts
> +export type GetGenerations = {
fixed

2023-05-06 10:34 UTC, BorchBe99 commented on server/src/trainee/traineeTypes.ts
> +export type GetMentorsOfGeneration = {
fixed

2023-05-06 10:35 UTC, BorchBe99 commented on server/src/trainee/traineeTypes.ts
> +export type GetInternalProjectOfGeneration = {
fixed

2023-05-06 10:36 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      [req.body.generation_ID]
fixed

2023-05-06 13:18 UTC, LennartRukower requested changes

2023-05-06 13:18 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> + * @param req generationID
```suggestion
 * @param {Request} req request object
  * @param {number} req.body.generationID
```

2023-05-06 14:48 UTC, LennartRukower requested changes
Needs work

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      FROM generation WHERE 1`,
Remove `WHERE 1`

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +router.get("/trainee-choice", authController.restrictRoutes([14], false), traineeController.retrieveTraineeChoice);
Change to `/generations/:id/trainee-choice`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +router.get("/trainee-generations", authController.restrictRoutes([14], false), traineeController.retrieveGenerations);
Change to `/generations`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +  "/trainee-generations-mentor",
Change to `/generations/:id/mentors`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +  "/internal-projects-of-generation",
Change to `/generations/:id/internal-projects`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +router.post("/trainee-add-mentor", authController.restrictRoutes([14], false), traineeController.addMentor);
Change to `/generations/:id/add-mentor/:member_id`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +  "/trainee-choice-deadline-set",
Change to `/generations/:id/set-deadline`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeRoutes.ts
> +router.patch("/trainee-assignment", authController.restrictRoutes([14], false), traineeController.setTraineeAssignment);
Change to `/:id/assignment`.

2023-05-06 14:48 UTC, LennartRukower commented on server/src/trainee/traineeController.ts
> +      [req.body.generationID]
Change to `req.params.id`.

2023-05-06 14:59 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +  * @param {number} req.body.generationID
fixed

2023-05-06 15:00 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      FROM generation WHERE 1`,
fixed

2023-05-06 15:12 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +router.get("/trainee-choice", authController.restrictRoutes([14], false), traineeController.retrieveTraineeChoice);
fixed

2023-05-06 15:15 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +router.get("/trainee-generations", authController.restrictRoutes([14], false), traineeController.retrieveGenerations);
fixed

2023-05-06 15:22 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +  "/trainee-generations-mentor",
fixed

2023-05-06 15:27 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +  "/internal-projects-of-generation",
fixed

2023-05-06 15:32 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +router.post("/trainee-add-mentor", authController.restrictRoutes([14], false), traineeController.addMentor);
fixed

2023-05-06 15:37 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +  "/trainee-choice-deadline-set",
fixed

2023-05-06 15:40 UTC, BorchBe99 commented on server/src/trainee/traineeRoutes.ts
> +router.patch("/trainee-assignment", authController.restrictRoutes([14], false), traineeController.setTraineeAssignment);
fixed

2023-05-06 15:41 UTC, BorchBe99 commented on server/src/trainee/traineeController.ts
> +      [req.body.generationID]
fixed

2023-05-21 11:29 UTC, LennartRukower requested changes
Very good solution. I like it a lot!

I found two small issues regarding the sent response codes and the check for existing resources in the database.

2023-05-21 11:29 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +    res.status(500).send("Generation does not exist");
Instead of the status code 500 you should send the status code 404, because the generation does not exist.

2023-05-21 11:29 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +    res.status(500).send("Member does not exist");
Instead of the status code 500 you should send the status code 404, because the member does not exist.

2023-05-21 11:29 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +  const resultFirstQuery = await database.query(`SELECT mitgliedID FROM mitglied WHERE mitgliedID = ?`, [req.params.id]);
You should also check if the provided "internesprojektID", "mentorID" and "ressortID" are valid (not null and exist in the database). If the ids are not valid send a 422 error response (422 means, that the request is semantically incorrect).

2023-05-21 11:29 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +    res.status(500).send("Generation does not exist");
Instead of the status code 500 you should send the status code 404, because the member does not exist.

2023-05-21 11:29 UTC, LennartRukower commented on server/src/trainees/traineesController.ts
> +  const resultFirstQuery = await database.query(`SELECT generationID FROM generation WHERE generationID = ?`, [req.params.id]);
You should also check if the second request parameter (the member id) is valid (not null and exist in the database). If the id is not valid send a 404 error response (404 and not 422 because the resource we want to access - in this case the generation and the member - does not exist).

2023-05-21 12:57 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +    res.status(500).send("Generation does not exist");
fixed

2023-05-21 12:57 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +    res.status(500).send("Member does not exist");
fixed

2023-05-21 16:22 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +  const resultFirstQuery = await database.query(`SELECT mitgliedID FROM mitglied WHERE mitgliedID = ?`, [req.params.id]);
fixed

2023-05-21 16:29 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +    res.status(500).send("Generation does not exist");
fixed

2023-06-11 09:49 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +  const resultFirstQuery = await database.query(`SELECT generationID FROM generation WHERE generationID = ?`, [req.params.id]);
fixed

2023-06-11 09:51 UTC, LennartRukower requested changes
A few minor issues

2023-06-11 09:57 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +  const idChecks = checkForIDs([req.params.id], ["generationID"], ["generation"]);
fixed

2023-06-11 10:02 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +        `SELECT ${idNames[index]} FROM ${tables[index]} WHERE ${idNames[index]} = ${ids[index]}`,
fixed

2023-06-11 10:03 UTC, BorchBe99 commented on server/src/trainees/traineesController.ts
> +      if (Array.isArray(resultQuery) && resultQuery.length !== 0) {
fixed

2023-06-11 13:26 UTC, LennartRukower commented
LGTM! Great work!

2023-06-11 13:26 UTC, LennartRukower approved these changes

2023-06-11 13:27 UTC, merged