#83 client edit link at departmentoverview
jbt-it/neomdb pull request #232
Opened 2022-12-15 17:36 UTC by LennartRukower

- Added department dialog component
- Added update department route
- Added api call to update departments

2023-05-15 14:17 UTC, johannesfbraun requested changes
There are a lot of small changes not necessarily pertaining to the actual pull. Should this not be a different pull request?

2023-05-15 14:17 UTC, johannesfbraun commented on client/src/ts/global/components/DepartmentDialog.tsx
> +        if (err.response.status === 401) {
"export const updateDepartmentInfo" cannot throw an 401 exception. Is this done in authcontroller?

2023-05-15 14:17 UTC, johannesfbraun commented on server/src/members/membersRoutes.ts
> +  authController.restrictRoutes(ALL_PERMISSIONS, false),
Does this check for Permissions and return the 401 ERROR?

2023-05-15 14:17 UTC, johannesfbraun commented on server/src/members/membersController.ts
> +    ])
Why is the Wiki link not done here?

2023-05-16 15:44 UTC, LennartRukower commented on client/src/ts/global/components/DepartmentDialog.tsx
> +        if (err.response.status === 401) {
A 401 Error is always thrown when the user is not authenticated (anymore).

2023-05-21 10:49 UTC, LennartRukower commented on client/src/ts/global/components/DepartmentDialog.tsx
> +                Änderungen speichern
Good point :)

2023-05-21 10:51 UTC, LennartRukower commented on server/src/members/membersController.ts
> +    ])
Because it does not yet exist in the database. That's why you can not change it in the frontend either.

The Wiki Button was already implemented, but to reduce confusion I will delete it from the frontend for now.

2023-05-21 11:47 UTC, LennartRukower commented on server/src/members/membersRoutes.ts
> +  authController.restrictRoutes(ALL_PERMISSIONS, false),
It does check for permissions, but this is something I planned to rework.
Because it is not correctly implemented yet.

2023-05-21 11:49 UTC, LennartRukower commented
Remaining ToDos:

- [ ] Add middleware function to check if a user is the director of a department
- [ ] Add correct conditional rendering of the edit button

2023-06-12 14:07 UTC, johannesfbraun requested changes
Pretty good, just some minor questiosn

2023-06-22 18:07 UTC, johannesfbraun commented on server/src/middleware/authorization.ts
> + * @returns 403 if user is not permitted to access the department
I do not think this is obvious to everyone. You could also mention this in the _info.md file.

2023-06-22 18:09 UTC, johannesfbraun commented on server/src/middleware/authorization.ts
> + * @param res Response object
I don't agree. The info "object" is not sufficiently descriptive imo. 
Please explain what type of object is sent and received.

2023-06-23 20:31 UTC, LennartRukower commented on server/src/middleware/authorization.ts
> + * @returns 403 if user is not permitted to access the department
This is the basic functionality of express. I cannot explain every module we use.
I will continuously update documentation like _info.md, but this is not part of this pr!

2023-06-23 20:33 UTC, LennartRukower commented on server/src/middleware/authorization.ts
> + * @param res Response object
In almost no controller function are request and response objects explained.
When performing the backend refactoring I am going to check what should be consistently documented, but this is not sth. I would do in this pr!

2023-06-24 07:44 UTC, johannesfbraun commented on server/src/middleware/authorization.ts
> + * @returns 403 if user is not permitted to access the department
Yes i get your point. I think it is always a tradeoff between developing the neomdb fast and teaching new members a lot.

2023-06-24 07:56 UTC, johannesfbraun commented on server/src/middleware/authorization.ts
> + * @param res Response object
Not doing something in the past is not a valid reason for not doing it now. 
Me proposed solution would be something like `@param req Request object (auth token; department id).
Do you really think this is over the top?

2023-06-24 14:07 UTC, LennartRukower commented on server/src/middleware/authorization.ts
> + * @param res Response object
That is not what I am saying.
I don't think it makes sense to witheld a pr just because of one sentence if we want to refactor the whole backen.

But you can make a `code suggestion`, than I will just accept it.

2023-06-29 10:09 UTC, johannesfbraun commented on server/src/middleware/authorization.ts
> + * @param req Request object
```suggestion
 * @param req Request object (auth token; department id)
```

2023-06-29 10:18 UTC, johannesfbraun approved these changes
LGTM

2023-06-29 10:18 UTC, merged