#103 fix  server forgot password server sends new password
jbt-it/neomdb pull request #244
Opened 2023-06-11 10:17 UTC by johannesfbraun

create link first:
Patch:
https://localhost:3030/auth/forgot-password
Header:
Referer: http://localhost:3000/#/login
body(json):
{
    "email": "w.luft@studentische-beratung.de"
}

Then Update the PW:
Patch:
https://localhost:3030/auth//reset-forgot-password
Header:
Referer: http://localhost:3000/#/login
body(json):
{
    "email": "w.luft@studentische-beratung.de",
    "key":"$2a$10$jbDm3.DbNHVQGyRYNPWBYe9cBUr95BPygfdoB8M2YqBeUz23T6x4u",
    "newPassword":"s3cre7"
}
closes #103

2023-06-11 10:50 UTC, Prschmidt reviewed
Test

2023-06-11 10:50 UTC, Prschmidt commented on server/src/global/auth/authController.ts
> +        .query(
Test

2023-06-13 08:21 UTC, LennartRukower requested changes
Nice work!
I did not check the functionality yet, but I have a few small suggestions on my side.

2023-06-13 08:21 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +      if (result.length !== 0) {
Please reverse the if check such that if length is 0 send 200 status code.
Doing this only indents the res.status(200).send() and makes the code more readable.

2023-06-13 08:21 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +        if (result[0].datediff < 5) {
Please reverse the if check such that if dateDiff is smaller or equal to 5 send 200 status code.
Doing this only indents the res.status(200).send() and makes the code more readable.

2023-06-13 08:21 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +      if (result.length !== 0) {
After the `res.status(200).send()` you can use a `return;` such that you do not need an else block.

2023-06-13 08:21 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +        if (result[0].datediff < 5) {
After the `res.status(200).send()` you can use a `return;` such that you do not need an else block.

2023-06-22 18:26 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +      if (result.length !== 0) {
I personally find it more complicated the way you propose it, as having a res.status(200).send() disrupts the logical progression for me.

2023-06-22 18:34 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +        if (result[0].datediff < 5) {
I personally find it more complicated the way you propose it, as having a `res.status(200).send()` disrupts the logical progression for me.

2023-06-22 18:36 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +        if (result[0].datediff < 5) {
For me the way i did it is more logical, as i have the complete yes path as one and afterwards the no paths.

2023-06-27 12:22 UTC, LennartRukower requested changes
Good job resolving some of my issues!
But there are two unresolved issues of mine still open.

2023-06-27 12:22 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +                    const transport = nodemailer.createTransport({
@johannesfbraun, are you going to resolve this issue or do you not agree with me?

2023-06-27 12:22 UTC, LennartRukower commented on server/src/global/auth/authController.ts
> +                        pass: "pQam721?", // PW
@johannesfbraun, are you going to resolve this issue or do you not agree with me?

2023-06-29 11:05 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +                        pass: "pQam721?", // PW
No I totally agree!

2023-06-29 11:12 UTC, johannesfbraun commented on server/src/global/auth/authController.ts
> +                    const transport = nodemailer.createTransport({
I an not sure about this, as most of this would be different for each sent mail. Hence, I think the modularity and reusability would be marginal. But tell me if you disagree :)

2023-08-21 17:50 UTC, JanMueller31 approved these changes

2023-08-21 17:50 UTC, JanMueller31 commented on server/src/global/auth/authController.ts
> +                    const transport = nodemailer.createTransport({
Added this as a todo the transport should be placed in a separate file.

2023-08-21 17:52 UTC, JanMueller31 commented on server/package.json
> +    "jsonwebtoken": "^8.5.1",
changed to 9.0.0

2023-09-22 11:42 UTC, merged