296 create display component
jbt-it/neomdb pull request #297
Opened 2023-09-26 18:25 UTC by JanMueller31

Created a component that can display text, lists or checkboxes in a simple way.

How to check:
Go to http://localhost:3000/#/modularedarstellungtest and look if the fields are displayed correctly.

Go to the InfoSectionTest file and change some values to see how and if the component works.

2023-09-26 19:27 UTC, LennartRukower requested changes
Great work!

![image](https://github.com/jbt-it/neomdb/assets/45009167/565133b4-b1bf-4d76-829c-40eeb72c2763)
![image](https://github.com/jbt-it/neomdb/assets/45009167/b58b01ac-7d90-4990-9054-e44c8ae25040)
On smaller screens the Card and the multi-line text have a weird behavior.

When mobile responsiveness is not in scope of this PR, create a new issue addressing this problem.

2023-09-26 19:27 UTC, LennartRukower commented on client/src/ts/global/components/InfoSection.tsx
> +                field.value === "true" || field.value === "Ja" || field.value === true ? (
Why are all these value checks necessary?
Should the value of the checkbox not simply be true?

2023-09-26 20:42 UTC, JanMueller31 commented on client/src/ts/global/components/InfoSection.tsx
> +                field.value === "true" || field.value === "Ja" || field.value === true ? (
Depending on the DB value for each field, since I didn't check for every possible value. If it is stored as "Ja"/"Nein" in the db it wouldn't work

2023-09-27 16:50 UTC, LennartRukower commented on client/src/ts/global/components/InfoSection.tsx
> +                field.value === "true" || field.value === "Ja" || field.value === true ? (
But this is sth. that imo should be handled outside of this general component.
The use case specific processing of db values should not happen in here.

2023-09-27 17:25 UTC, LennartRukower approved these changes
Great work!

2023-09-28 10:34 UTC, merged