#352 server add event form
jbt-it/neomdb pull request #395
Opened 2024-02-22 20:33 UTC by LennartRukower

**How to test:**
- Start server
- Navigate to swagger (http://localhost:3030/api/docs)
- Test all events routes
- Run the events tests

2024-04-01 11:28 UTC, JanMueller31 submitted a review, later dismissed
Server crashes when updating an event with already existing organizers with error code 500:
error: Caught unknown error for /api/events/55: QueryError: Caught error while adding member with id 8167 to event with id 55: Error: Duplicate entry '55-8167' for key 'mitglied_has_event.PRIMARY'


With getEvent the eventID is not send to the frontend.

When successfully adding an organizer they have the role "Teilnehmer" in the db instead of "Organisator"



Also tests are somewhat failing:
error TS2322: Type '{ name: string; location: string; startDate: string; endDate: string; startTime: string; endTime: string; registrationStart: string; registrationEnd: string; maxParticipants: number; organizers: { ...; }[]; description: string; type: string; }' is not assignable to type 'UpdateEventRequest'.
      Object literal may only specify known properties, and 'name' does not exist in type 'UpdateEventRequest'.
      
A fix UpdateEventRequest consists of an Event and Organizers. Just wrap the event details in an event object.

2024-04-11 18:20 UTC, LennartRukower commented
Wait with review and implementation until #407 is merged.

2024-12-05 16:21 UTC, arisb1470 requested changes
Whenever you change an Event with PUT and the new eventId doesn`t match the old one, a new Event is created instead

2024-12-06 22:16 UTC, arisb1470 requested changes
- Leaving fields like name, description and location empty, simply leaves the fields unchanged
- As updating an event without those fields in the request body fails, it isn`t possible to update an event to not have a location or description
- It is possible to set the start date and time, as well as the registration start after the end date, time and registration end 
- It is possible to update events to not have organizers, is that intentional?

2025-01-05 16:45 UTC, LennartRukower commented
> * Leaving fields like name, description and location empty, simply leaves the fields unchanged
> * As updating an event without those fields in the request body fails, it isn`t possible to update an event to not have a location or description
> * It is possible to set the start date and time, as well as the registration start after the end date, time and registration end
> * It is possible to update events to not have organizers, is that intentional?

- Fields can now be empty and should be correctly updated.
- Start date/time can no longer be after end date/time.
- It is ok to remove organizers such that no organizer is there for now. We will evaluate at a later point, if we need to restrict this.

2025-03-08 15:06 UTC, arisb1470 approved these changes
looks great

2025-03-08 15:35 UTC, merged