422 implement react query trainees
jbt-it/neomdb pull request #423
Opened 2024-05-24 18:03 UTC by JanMueller31

Removed the api calls from the frontend components and created useTrainees. useTraineeGeneration amd useInternalProjectDetails.

Check if the data in these files is retrieved properly:
- TraineeSection
- InternalProject

How to check: check if every functionality related to backend calls works as expected
- admit a new trainee (TraineeSection) -> all requirements have to be set and memberstatus has to be "Trainee"
- Change IP Details
- Add / Remove IP member
- Add / Remove IP QMs

2024-06-13 15:47 UTC, LennartRukower requested changes
Good work! I have a few small issues.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/components/members/trainees/AddInternalProjectDialog.tsx
> +  const { trainees } = useTrainees();
Components should be as "dumb" as possible. Therefore move the trainees up and use props drilling.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/components/members/trainees/TraineeSectionTable.tsx
> +  const { admitTrainee } = useTrainees();
Components should be as "dumb" as possible. Therefore move the admitTrainee function up and use props drilling.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/components/members/DepartmentDialog.tsx
> +  const { updateDepartmentDetails } = useDepartments();
Components should be as "dumb" as possible. Therefore move the updateDepartmentDetails up and use props drilling.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/internalProjects.ts
> +  return await api.get<InternalProjectDto>(`/trainees/ip/${internalProjectId}`);
Is this explicit type declaration necessary?

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/internalProjects.ts
> +  return await api.get<InternalProjectDto[]>(`/trainees/ips/current`);
Is this explicit type declaration necessary?

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/internalProjects.ts
> +  return await api.get<InternalProjectDto[]>(`/trainees/ips/all`);
Is this explicit type declaration necessary?

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/internalProjects.ts
> +  return await api.put<InternalProjectDto>(`/trainees/ip/${internalProject.internalProjectId}`, internalProject);
Is this explicit type declaration necessary?

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/members.ts
> +  return await api.get<MemberPartialDto[]>("/members/");
Is this explicit type declaration necessary?

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/members.ts
> +  return await api.get<MemberDetailsDto>(`/members/${memberId}`);
Is this explicit type declaration necessary?

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/members.ts
> +  return await api.get(`/members/${id}/image`);
If explicit typing is necessary, do it here too.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/members.ts
> +  return await api.get("/members/languages");
If explicit typing is necessary, do it here too.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/members.ts
> +  return await api.get("/members/edv-skills");
If explicit typing is necessary, do it here too.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/permissions.ts
> +  return await api.get("/members/permissions");
If explicit typing is necessary, do it here too.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/api/permissions.ts
> +  return await api.get("/members/permission-assignments");
If explicit typing is necessary, do it here too.

2024-06-13 15:47 UTC, LennartRukower commented on client/src/hooks/members/useDepartments.ts
> +  const departments = (departmentsData?.data as DepartmentDetailsDto[]) || [];
This can be applied to all hook data: Would this be better for readability?
```suggestion
  const departments = departmentsData?.data || [];
```

2024-06-13 15:47 UTC, LennartRukower commented on client/src/hooks/members/useMemberDetails.ts
> +  const memberDetails = memberDetailsData && (memberDetailsData.data as MemberDetailsDto);
This is not very intuitive.
Suggestion:

```suggestion
  const memberDetails = memberDetailsData?.data || null;
```

2024-06-13 15:47 UTC, LennartRukower commented on client/src/hooks/members/useMemberDetails.ts
> +  const memberImage = memberImageData ? (memberImageData.data as MemberImage) : null;
```suggestion
  const memberImage = memberImageData.data || null;
```

2024-06-13 15:47 UTC, LennartRukower commented on client/src/hooks/trainees/useTraineeGeneration.ts
> +const useTraineeGeneration = (generationID: number) => {
Please add a short comment

2024-07-08 18:16 UTC, JanMueller31 commented on client/src/pages/members/PermissionsOverview.tsx
> +  const membersForAutocomplete: AutocompleteValue[] = members.map((member: MemberPartialDto) => ({
Members won't load correctly when using useEffect, even when putting the autocompleteValues in a separate useEffect

2024-07-08 18:21 UTC, JanMueller31 commented on client/src/pages/members/PermissionsOverview.tsx
> +  const membersForAutocomplete: AutocompleteValue[] = members.map((member: MemberPartialDto) => ({
Members won't load correctly when using useEffect, even when putting the autocompleteValues in a separate useEffect

2024-10-26 08:06 UTC, LennartRukower approved these changes
LGTM

2024-10-26 08:10 UTC, LennartRukower requested changes
In `DepartmentOverview` there is the following type error in line 293:
Type '(departmentDetails: DepartmentDetailsDto) => Promise<AxiosResponse<UpdateDepartmentDto, any>>' is not assignable to type '(departmentDetails: DepartmentDetailsDto) => Promise<AxiosResponse<DepartmentDetailsDto, any>>'.
  Type 'Promise<AxiosResponse<UpdateDepartmentDto, any>>' is not assignable to type 'Promise<AxiosResponse<DepartmentDetailsDto, any>>'.
    Type 'AxiosResponse<UpdateDepartmentDto, any>' is not assignable to type 'AxiosResponse<DepartmentDetailsDto, any>'.
      Type 'UpdateDepartmentDto' is missing the following properties from type 'DepartmentDetailsDto': departmentId, name, shortName, jbtEmail

2025-03-28 16:19 UTC, LennartRukower approved these changes
LGTM

2025-03-28 16:19 UTC, merged