465 client application portal
jbt-it/neomdb pull request #508
Opened 2024-09-17 21:16 UTC by JanMueller31

How to test:
- go to /bewerbung and apply on desktop and on mobile

2024-10-14 09:57 UTC, arisb1470 commented
Looks good! Just a few things I noticed:

First Page: There are no restrictions on what can be entered in the text fields (date of birth can be in the future, phone number can contain letters, email address can be anything as well).

Third page: You cannot specify more than one "Berufliche Tätigkeit"
For internships - The button to remove an internship is right next to the fist text field. It might be better for it to be above the text fields.

Last page: At "Auswahlwochenende", you can only choose at most one day at which you aren't available.

2024-11-19 21:23 UTC, JanMueller31 commented
> Looks good! Just a few things I noticed:
> 
> First Page: There are no restrictions on what can be entered in the text fields (date of birth can be in the future, phone number can contain letters, email address can be anything as well).
> 
> Third page: You cannot specify more than one "Berufliche Tätigkeit" For internships - The button to remove an internship is right next to the fist text field. It might be better for it to be above the text fields.
> 
> Last page: At "Auswahlwochenende", you can only choose at most one day at which you aren't available.

The "Auswahlwochenende" is implemented as suggested in the issue and as in our current application form

2024-12-05 17:16 UTC, arisb1470 reviewed
For every section you can unfold and add multiple instances, that has mandatory fields (eg. Praktika, Sprachen, IT-Skills), even filling those fields out doesn't allow you to go to the next page.

2025-01-04 12:37 UTC, arisb1470 requested changes
Looks great! Only a few small things I noticed

2025-01-04 12:37 UTC, arisb1470 commented on client/src/types/applicationTypes.ts
> +// Definition of the ApplicationHiwiStudentJob type
Maybe check the wording

2025-01-04 12:37 UTC, arisb1470 commented on client/src/types/applicationTypes.ts
> +// Definition of the ApplicationHiwiStudentJobError type
Maybe check the wording

2025-01-04 12:37 UTC, arisb1470 commented on client/src/components/application/ApplicationForm.tsx
> +  // check if all required fields of the personal data step are filled
Check the wording

2025-01-04 12:37 UTC, arisb1470 commented on client/src/components/application/ApplicationForm.tsx
> +    console.log(completed);
Are the console logs still necessary?

2025-01-04 12:37 UTC, arisb1470 commented on client/src/components/application/steps/PersonalDataStep.tsx
> +              Bild hochladen *
Maybe add an indication that the picture was uploaded successfully

2025-01-06 17:14 UTC, JanMueller31 commented on client/src/components/application/ApplicationForm.tsx
> +    console.log(completed);
Will be removed in #455

2025-03-08 10:22 UTC, arisb1470 approved these changes
Looks beautiful!

2025-03-08 10:46 UTC, merged