455 server add application portal
jbt-it/neomdb pull request #509
Opened 2024-09-18 21:25 UTC by JanMueller31

How to test:
- create a new application with /bewerbungen
- check the db if the trainee application has been saved
- run the applicaion test

2024-10-26 09:58 UTC, arisb1470 commented
There seems to be a problem with the handleSubmission 
![image](https://github.com/user-attachments/assets/79a6b397-13ad-4992-a43d-9d7c9af2d42c)
A 500 Internal Server Error gets thrown

2024-10-26 10:22 UTC, arisb1470 requested changes
This is what I noticed at the backend tests

2024-10-26 10:22 UTC, arisb1470 commented on server/test/resources/application/applicationRoutes.test.ts
> +      expect(response.status).toBe(201);
The following error gets thrown: Test application routes > POST / create application > should return 201 for creating new application
Error: expect(received).toBe(expected) // Object.is equality

Expected: 201
Received: 500Jest

2024-11-19 21:26 UTC, JanMueller31 commented on server/test/resources/application/applicationRoutes.test.ts
> +      expect(response.status).toBe(201);
It passed for me. I need more information to make a change

2024-11-19 22:26 UTC, LennartRukower commented on server/test/resources/application/applicationRoutes.test.ts
> +      expect(response.status).toBe(201);
@JanMueller31 What information do you need?
@JanMueller31, @arisb1470 Are you sure, that you were on the correct branch?
Sometimes there are multiple branches that are depending on each other.

2024-11-19 23:56 UTC, JanMueller31 commented on server/test/resources/application/applicationRoutes.test.ts
> +      expect(response.status).toBe(201);
@LennartRukower I need the error the server throws to clarify what went wrong. Currently I only understand that it throws a 500 and whats received is not whats expected

2025-01-04 12:51 UTC, arisb1470 requested changes
Same error persists
![image](https://github.com/user-attachments/assets/f02fc536-6623-4a9c-894e-229721589a3c)

Error saving application: [Error: ENOENT: no such file or directory, open 'C:\Users\arisb\Desktop\NeoMDB\neomdb\server\assets\applicants\307.png'] {
[0]   errno: -4058,
[0]   code: 'ENOENT',
[0]   syscall: 'open',
[0]   path: 'C:\\Users\\arisb\\Desktop\\NeoMDB\\neomdb\\server\\assets\\applicants\\307.png'
[0] }

2025-03-08 11:02 UTC, arisb1470 commented
I left out some issues that you have already resolved in 465, however I still noticed: 

- birthdate can still be far in the past (>1000 years)
- maybe consider setting the conditions for the dates a bit looser, maybe 20 years for "Studienbeginn", "Berufl Ausbildung", "Berufl Tätigkeit", "Praktika"
- You can still only set a single "Berufliche Tätigkeit"

2025-03-08 15:24 UTC, arisb1470 approved these changes
Looks good

2025-03-10 17:29 UTC, merged